### ISSUE TITLE
作为sdk提供给第三方用，插件不支持高版本gradle

### ISSUE THREAD

**Issue by liangxiwei** [eleme/lancet#22]
A是主工程，B集成了lancet,A使用B的时候，会提示下面的错。
* What went wrong:
Execution failed for task ':app:transformClassesWithLancetForDebug'.
> java.lang.IllegalAccessError: tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class me.ele.lancet.plugin.internal.context.DirectoryContentProvider

具体可以把饿了么另外的一个名为trojan的项目升级一下gradlewrapper的版本,就会发现有一样的错。

**Comment by liangxiwei** [comment]
我自己改好了，回头给你们提个pr吧，这个项目估计也不维护了吧

**Comment by liangxiwei** [comment]
具体原因是高版本gradle里面，插件用到一个guava的类，刚好该方法被弃用并且变成package可见，所以一运行就报错。

**Comment by liuhuiAndroid** [comment]
我也遇到了类似的问题，这个项目不维护了也是尴尬，准备不打算用了

**Comment by liangxiwei** [comment]
> 准备

这个项目易用性挺好的，我们现在是自己编译自己发布

**Comment by penneryu** [comment]
已在1.0.5版本中解决。
