### ISSUE TITLE
对This.get()的疑问？？

### ISSUE THREAD

**Issue by Zihao-Wu** [eleme/lancet#27]
看readMe介绍里说，Proxy里不可以用This.get(),但我试了下，是可以的，请问是添加支持了吗？
版本：'me.ele:lancet-base:1.0.5'
如下：This.get()是可以获取到View的
    @TargetClass(value = "android.view.View",scope = Scope.SELF)
    @Proxy(value = "setOnClickListener")
    public void setOnClickListener(View.OnClickListener l) {
        System.out.println("setOnClickListener"+" l:"+ l+" "+This.get());
        Origin.callVoid();
    }

**Comment by sparkfengbo** [comment]
中英翻译的内容有出入，英文版说putField和getField的This只能在Insert使用，但是中文版说成了This只能在Insert使用，这种翻译都没有校准。

**Comment by Zihao-Wu** [comment]
> 中英翻译的内容有出入，英文版说putField和getField的此只能在插入使用，但是中文版说变成此只能在插入使用，这种翻译都没有校准。

谢了，老哥，已经换AspectJ 来实现AOP 了，这项目不维护，只能弃坑
