### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.io.Files.fileTraverser()Lcom/google/common/graph/Traverser;

### ISSUE THREAD

**Issue by ihrthk** [eleme/lancet#32]

**Comment by ihrthk** [comment]
me.ele:lancet-plugin:1.0.5

**Comment by TJundx** [comment]
一样是这个问题

**Comment by TJundx** [comment]
![image](https://user-images.githubusercontent.com/20396159/67845973-6228e400-fb3b-11e9-8fb3-c4be44030527.png)

**Comment by TJundx** [comment]
配置 gradle 3.0.1
![image](https://user-images.githubusercontent.com/20396159/67846671-8f29c680-fb3c-11e9-9975-6b9218915bfb.png)

**Comment by penneryu** [comment]
可以参照问题 https://github.com/eleme/lancet/issues/25 ，这个之后会发版本解决。 @ihrthk @KwanTang324
