### ISSUE TITLE
随便写了个Android例子，都没生效

### ISSUE THREAD

**Issue by haizhiyun** [eleme/lancet#48]
按照文档提供的子，hook 下log.i 没有生效，变以没问题，有人使用生效的吗

**Comment by DarkAdventurerr** [comment]
应该是你项目中的com.android.tools.build:gradle版本高了导致的，或者自己fork一份源码修改一下，lancet很久没有更新了，用的还是ASM5

**Comment by DarkAdventurerr** [comment]
见issue #42

**Comment by haizhiyun** [comment]
> 见issue #42

感谢，后面试试
